In [1]:
import numpy as np
from numpy.linalg import solve

In [2]:
def input1():
    print("Enter matrix1")

    r1=int(input("Enter no of Rows:"))
    c1=int(input("Enter no of columns:"))

    print("Enter the elements row by row with space separation:")

    values1=list(map(int,input().split()))
    if(len(values1)==r1*c1):


        matrix1=np.array(values1).reshape(r1,c1)
        print(matrix1)
        return r1,c1,matrix1
    else:
        print(" oops its a error ! ,enter the required no of entries")

In [3]:
def input2():
    print("Enter matrix2")
    r2=int(input("Enter no of Rows:"))
    c2=int(input("Enter no of columns:"))

    print("Enter the elements row by row with space separation:")

    values2=list(map(int,input().split()))
    if(len(values2)==r2*c2):
        matrix2=np.array(values2).reshape(r2,c2)
        print(matrix2)
        return r2,c2,matrix2
    else:
        print(" oops its a error ! ,enter the required no of entries")

In [4]:
def addition(m1,m2):
    mf=np.add(m1,m2)
    print(mf)

def subtraction(m1,m2):
    mf=np.subtract(m1,m2)
    print(mf)

def scalar_mul(m1,m2,i):
    mf1=np.dot(i,m1)
    print("the scalar ouput of matrix1:\n",mf1)
    mf2=np.dot(i,m2)
    print("the scalar ouput of matrix2:\n",mf2)

def ele_mul(m1,m2):
    mf=np.multiply(m1,m2)
    print(mf)
    
def mat_mul(m1,m2):
    mf=np.matmul(m1,m2)
    print(mf)
    
def Mat_transpose(m1,m2):
    mf1=m1.T
    mf2=m2.T
    print("the transpose of matrix1:\n",mf1)
    print("the transpse of matrix2:\n",mf2)
    

def mat_trace(m1,m2):
    t1=m1.trace()
    t2=m2.trace()
    print("the trace of matrix1:\n",t1)
    print("the trace of matrix2:\n",t2)
    
    

def mat_det(mat1,mat2):
    det1=np.linalg.det(mat1)
    det2=np.linalg.det(mat2)
    print("det of Matrix1 :",det1)
    print("det of Matrix2 :",det2)

def mat_inv(mat1,mat2):
    inv1=np.linalg.inv(mat1)
    inv2=np.linalg.inv(mat2)
    print("The inverse of Matrix-1 : \n",inv1)
    print("The inverse of Matrix-2 :\n ",inv2)

def mat_eigen(mat1,mat2):
    w1,v1=np.linalg.eig(mat1)
    w2,v2=np.linalg.eig(mat2)
    print("The eigen values of Matrix-1 :\n ",w1)
    print("The eigen vector of Matrix-1 :\n ",v1)
    print("The eigen values of Matrix-2 :\n ",w2)
    print("The eigen vector of Matrix-2 :\n ",v2)

def mat_solve(mat1,mat2,r1,r2):
  print("Enter the Constants of Matrix-1 : ")
  li1=[]
  for i in range(0,r1):
    ele1=int(input("Enter the Constant for the equation : "))
    li1.append(ele1)
  print("Enter the Constants of Matrix-2 : ")
  li2=[]
  for i in range(0,r2):
    ele2=int(input("Enter the Constant for the equation : "))
    li2.append(ele2)
  solve1=np.linalg.solve(mat1,li1)
  solve2=np.linalg.solve(mat2,li2)
  print("The solution of matrix1 is\n",solve1)
  print("The solution of matrix2 is\n",solve2)    

In [5]:
def menu():
    print(" ######### MENU ########")
    print("1. Matrix Addition")
    print("2. Matrix Subtraction")
    print("3. Scalar Matrix Multiplication")
    print("4. Elementwise Matrix Mulltiplication")
    print("5. Matrix Multiplication")
    print("6. Matrix Transpose")
    print("7. Trace of a Matrix")
    print("8. Solve system of Linear Equations")
    print("9. Determinant")
    print("10. Inverse")
    print("11. Eigen value and Eigen vector")
    print("12. Exit")
    print()

In [ ]:
r1,c1,matrix1=input1()
r2,c2,matrix2=input2()

while(True):
    menu()
    choice=int(input("Enter the option of your choice: "))
    if(choice==1):

        if(r1==r2 and c1==c2):
            addition(matrix1,matrix2)
        else:
            print("The Addition is not possible\n")

    elif(choice==2):
        if(r1==r2 and c1==c2):
            subtraction(matrix1,matrix2)
        else:
            print("The Subtraction is not possible\n")

    elif(choice==3):
        scalar=int(input("Enter scalar value: "))
        scalar_mul(matrix1,matrix2,scalar)

    elif(choice==4):
        if(r1==r2 and c1==c2):
            ele_mul(matrix1,matrix2)
        else:
            print("The Multiplication is not possible \n")

    elif(choice==5):
        if(c1==r2):
            mat_mul(matrix1,matrix2)
        else:
            print("The Multiplication is not possible \n")

    elif(choice==6):
        Mat_transpose(matrix1,matrix2)

    elif(choice==7):


        if(r1==c1 and r2==c2):
            mat_trace(matrix1,matrix2)
        elif(r1!=c1 and r2==c2):
            print("Trace can't be found for rectangular matrix(matrix1)\n")
            print("The Trace of Matrix-2 is: \n ",matrix2.trace())
        elif(r1==c1 and r2!=c2):
            print("Trace can't be found for rectangular matrix \n")
            print("The Trace of Matrix-1 is: \n ",matrix1.trace())
        else:
            print("Trace can't be found for rectangular matrix \n")

    elif(choice==8):
        mat_solve(matrix1,matrix2,r1,r2)

    elif(choice==9):
        if(r1==c1 and r2==c2):
            mat_det(matrix1,matrix2)
        elif(r1!=c1 and r2==c2):
            print("Determinant can't be found for rectangular matrix(matrix1)\n")
            print("The Determinant of Matrix-2 is:\n ",np.linalg.det(matrix2))
        elif(r1==c1 and r2!=c2):
            print("Determinant can't be found for rectangular matrix(matrix2)\n")
            print("The Determinant of Matrix-1 is:\n ",np.linalg.det(matrix1))
        else:
            print("Determinant can't be found for rectangular matrix\n")

    elif(choice==10):
        if(r1==c1 and r2==c2):
            mat_inv(matrix1,matrix2)
        elif(r1!=c1 and r2==c2):
            print("Inverse can't be found for rectangular matrix\n")
            print("The Inverse of Matrix-2 is: \n ",np.linalg.inv(matrix2))
        elif(r1==c1 and r2!=c2):
            print("Inverse can't be found for rectangular matrix\n")
            print("The Inverse of Matrix-1 is:\n ",np.linalg.inv(matrix1))
        else:
            print("Inverse can't be found for rectangular matrix \n")

    elif(choice==11):
        if(r1==c1 and r2==c2):
            mat_eigen(matrix1,matrix2)
        elif(r1!=c1 and r2==c2):
            print("Eigen values and vectors can't be found for rectangular matrix \n")
            print("The Eigen values and vectors of Matrix-2 is:\n ",np.linalg.eig(matrix2))
        elif(r1==c1 and r2!=c2):
            print("Eigen values and vectors can't be found for rectangular matrix \n")
            print("The Eigen values and vectors of Matrix-1 is:\n",np.linalg.eig(matrix1))
        else:
            print("Eigen values can't be found for rectangular matrix \n")

    elif(choice==12):
        break

Enter matrix1
Enter no of Rows:2
Enter no of columns:2
Enter the elements row by row with space separation:
1 2 3 4
[[1 2]
 [3 4]]
Enter matrix2
Enter no of Rows:2
Enter no of columns:2
Enter the elements row by row with space separation:
4 3 2 1
[[4 3]
 [2 1]]
 ######### MENU ########
1. Matrix Addition
2. Matrix Subtraction
3. Scalar Matrix Multiplication
4. Elementwise Matrix Mulltiplication
5. Matrix Multiplication
6. Matrix Transpose
7. Trace of a Matrix
8. Solve system of Linear Equations
9. Determinant
10. Inverse
11. Eigen value and Eigen vector
12. Exit

Enter the option of your choice: 1
[[5 5]
 [5 5]]
 ######### MENU ########
1. Matrix Addition
2. Matrix Subtraction
3. Scalar Matrix Multiplication
4. Elementwise Matrix Mulltiplication
5. Matrix Multiplication
6. Matrix Transpose
7. Trace of a Matrix
8. Solve system of Linear Equations
9. Determinant
10. Inverse
11. Eigen value and Eigen vector
12. Exit

Enter the option of your choice: 2
[[-3 -1]
 [ 1  3]]
 ######### MENU ##